apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datahub-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: datahub.shortbread.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datahub
                port:
                  number: 3000
