# WARNING: This is a template. Do not commit real secrets!
# Replace values and apply manually, or use a secrets manager.
apiVersion: v1
kind: Secret
metadata:
  name: datahub-postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: datahub
  POSTGRES_PASSWORD: 632027b09c3da5d7ae1e02f51767ecc3f557acf7d22bee6fc3d850317fb95337
  DATABASE_URL: postgresql://datahub:632027b09c3da5d7ae1e02f51767ecc3f557acf7d22bee6fc3d850317fb95337@datahub-postgres.datahub.svc.cluster.local:5432/datahub
